### ISSUE TITLE
Privacy Policy as HTML

### ISSUE THREAD

**Issue by OMGSoundboard** [OMGSoundboard/OMGSoundboard.github.io#39]
Google requests the Privacy Policy to be an active URL (no PDFs).
An active Privacy Policy should be available at [https://omgsoundboard.audio/privacy-policy/](https://omgsoundboard.audio/privacy-policy/).

**Comment by vidhyav656** [comment]
Do you have the content for the privacy policy page?

**Comment by OMGSoundboard** [comment]
> Do you have the content for the privacy policy page?

Yes, it's in `assets/legal/OMGSoundboard_PrivacyPolicy.html`.

**Comment by OMGSoundboard** [comment]
Thank you so much for your PR! 😍
Fixed in #42

**Comment by OMGSoundboard** [comment]
May you please enable the favicon for [https://omgsoundboard.audio/privacy-policy/](https://omgsoundboard.audio/privacy-policy/), @vidhyav656?
