### ISSUE TITLE
Add Mastodon Verification Link

### ISSUE THREAD

**Issue by OMGSoundboard** [OMGSoundboard/OMGSoundboard.github.io#54]
`<a rel="me" href="https://androiddev.social/@OMGSoundboard">Mastodon</a>`

We may add it on the homepage or just add it invisibly.

**Comment by vidhyav656** [comment]
Where to add this at homepage

**Comment by OMGSoundboard** [comment]
> Where to add this at homepage

May you please put it in the About section and call it Mastodon?

**Comment by vidhyav656** [comment]
Sure, will do. What is your website url?

**Comment by OMGSoundboard** [comment]
> Sure, will do. What is your website url?

What do you mean?
