### ISSUE TITLE
Put Files In .well-known Folder

### ISSUE THREAD

**Issue by OMGSoundboard** [OMGSoundboard/OMGSoundboard.github.io#67]
**Examples:**

[Deeplinks](https://play.google.com/console/about/deeplinks/): https://omgsoundboard.audio/.well-known/assetlinks.json --> [assetlinks.json](https://github.com/OMGSoundboard/OMGSoundboard.github.io/files/13822439/assetlinks.json)

[security.txt](https://en.wikipedia.org/wiki/Security.txt): [https://omgsoundboard.audio/.well-known/security.txt](https://omgsoundboard.audio/.well-known/security.txt) --> [security.txt](https://github.com/OMGSoundboard/OMGSoundboard.github.io/files/13822481/security.txt)

[MTA-STS policy](https://mxtoolbox.com/dmarc/details/mta-sts/what-is-mta-sts-record): https://mta-sts.omgsoundboard.audio/.well-known/mta-sts.txt --> [mta-sts.txt](https://github.com/OMGSoundboard/OMGSoundboard.github.io/files/13822492/mta-sts.txt)

**Comment by OMGSoundboard** [comment]
Do we have to configure something for Jekyll so that the three hyperlinks work, @vidhyav656?

**Comment by vidhyav656** [comment]
where do you want to addd this hyperlink?
